{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "swetrix.fullname" . }}-secrets
  labels:
    {{- include "swetrix.backend.labels" . | nindent 4 }}
  {{- with .Values.secrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  SECRET_KEY_BASE: {{ randAlphaNum 48 | b64enc }}
  DISABLE_REGISTRATION: {{ .Values.backend.registration.enabled | quote | b64enc }}
  OIDC_ENABLED: {{ .Values.backend.oidc.enabled 48 | quote | b64enc }}
{{- end }}
