{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "swetrix.fullname" . }}-secrets
  labels:
    {{- include "swetrix.backend.labels" . | nindent 4 }}
  {{- with .Values.secrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  SECRET_KEY_BASE: {{ randAlphaNum 48 | b64enc }}
  DISABLE_REGISTRATION: false
  OIDC_ENABLED: false
{{- end }}
