apiVersion: v2
name: swetrix
description: A Swetrix Helm chart for Kubernetes
type: application
version: 1.1.0
appVersion: "4.0.1"
dependencies:
  - name: redis
    version: "21.2.13"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: clickhouse
    version: "9.4.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: clickhouse.enabled
